# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aux_nbdsmooth <- function(A, N) {
    .Call('_graphon_aux_nbdsmooth', PACKAGE = 'graphon', A, N)
}

aux_preset <- function(vecgrid, n, id) {
    .Call('_graphon_aux_preset', PACKAGE = 'graphon', vecgrid, n, id)
}

